from models import *
Base.metadata.create_all(bind=engine)
session = Session()

user1 = User(username='olena', first_name='Olena',last_name='Pyrih',address='hfkhsiuf', email='olenka.pyrih@gmail.com', phone_number='0658951255', password='1')
user2 = User(username='sofiya', first_name='Sofiya',last_name='Hymon', address='ghdkdf', email='sofiyahymon@gmail.com', phone_number='0985266654', password='2')
user3 = User(username='andriy', first_name='Andriy',last_name='Malynovskyi', address='rtyuiwop', email='andriymalynovskyi@gmail.com', phone_number='0962645485', password='3')
session.add(user1)
session.add(user2)
session.add(user3)
session.commit()


category1=Category(name='missing')
category2=Category(name='job search')
category3=Category(name='job offer')
session.add(category1)
session.add(category2)
session.add(category3)
session.commit()
advertisement1 = Advertisement(description='I lost my bag', status=0, user=user1, category=category1)
advertisement2 = Advertisement(description='fghj', status=1, user=user2, category=category2)
advertisement3 = Advertisement(description='fgh', status=0, user=user3, category=category3)
advertisement4 = Advertisement(description='fgh', status=0, user=user2, category=category3)
# advertisement2 = Advertisement()
session.add(advertisement1)
session.add(advertisement2)
session.add(advertisement3)
session.add(advertisement4)
# session.add(advertisement2)
session.commit()
session.close()